version: '3'
services:
    jira:
        container_name: jira
        image: "atlassian/jira-software"
        volumes: 
            - ./atlassian-agent.jar:/var/atlassian/atlassian-agent.jar
            - ./mysql-connector-java-8.0.22.jar:/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/mysql-connector-java-8.0.22.jar
            - /data/jira:/var/atlassian/application-data/jira
        environment:
            - JAVA_OPTS="-javaagent:/var/atlassian/atlassian-agent.jar"
            - JVM_MINIMUM_MEMORY=1024m
            - JVM_MAXIMUM_MEMORY=1024m
            - JVM_RESERVED_CODE_CACHE_SIZE=512m
        ports: 
            - "8080:8080"
        restart: always
